# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
cache: packages
warnings_are_errors: true
os: linux
dist: bionic

jobs:
  include:
    - name: linux-bionic
      os: linux
      dist: bionic
      env: R_CODECOV=true
    - name: linux-xenial
      os: linux
      dist: xenial
    - name: osx-current
      os: osx
      before_install:
        - brew install curl
        - brew link --force curl
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

r_github_packages:
  - r-lib/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov()'; fi
  # - Rscript -e 'covr::coveralls()'
