# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
sudo: false
cache: packages
warnings_are_errors: true

r_packages:
- htmltools
- digest
- covr
- rmarkdown
- knitr

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::coveralls()'
