# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
sudo: required
cache: packages
warnings_are_errors: true

r_packages:
- htmltools
- digest
- covr
- rmarkdown
- knitr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
