# Travis's native R Image (http://docs.travis-ci.com/user/languages/r/)
language: r
sudo: false
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew install curl
        - brew link --force curl
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

r_packages:
- htmltools
- digest
- covr
- rmarkdown
- knitr

r_github_packages:
  - r-lib/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov()'; fi
  # - Rscript -e 'covr::coveralls()'
