language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew install curl
        - brew link --force curl
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode7.3
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

r_packages:
- r-lib/covr
- rstudio/rmarkdown
- yihui/knitr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
